using System.Collections.Generic;

namespace FlexLabs.Inky.Text.Fonts
{
    public static partial class DotMatrixBold
    {
        /// <summary>
        /// Simple Dot Bold matrix font, size 6
        /// </summary>
        public static readonly Dictionary<char, bool[,]> Size6 = new Dictionary<char, bool[,]>
        {
            [':'] = new bool[,]
            {
                { false, false,  },
                { false, false,  },
                { true, true,  },
                { true, true,  },
                { false, false,  },
                { true, true,  },
                { true, true,  },
                { false, false,  },
                { false, false,  },
            },
            [','] = new bool[,]
            {
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
                { false, true, true,  },
                { false, true, true,  },
                { true, true, false,  },
                { false, false, false,  },
            },
            ['.'] = new bool[,]
            {
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { true, true,  },
                { true, true,  },
                { false, false,  },
                { false, false,  },
            },
            ['-'] = new bool[,]
            {
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
                { true, true, true,  },
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
                { false, false, false,  },
            },
            ['_'] = new bool[,]
            {
                { false, false, false, false,  },
                { false, false, false, false,  },
                { false, false, false, false,  },
                { false, false, false, false,  },
                { false, false, false, false,  },
                { false, false, false, false,  },
                { true, true, true, true,  },
                { false, false, false, false,  },
                { false, false, false, false,  },
            },
            ['\''] = new bool[,]
            {
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
            },
            ['"'] = new bool[,]
            {
                { true, true, false, true, true,  },
                { true, true, false, true, true,  },
                { true, true, false, true, true,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
            },
            ['`'] = new bool[,]
            {
                { true, true,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
                { false, false,  },
            },
            ['0'] = new bool[,]
            {
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['1'] = new bool[,]
            {
                { false, false, true, true, false, false,  },
                { false, true, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['2'] = new bool[,]
            {
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['3'] = new bool[,]
            {
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, true, true, true, false,  },
                { false, false, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['4'] = new bool[,]
            {
                { false, false, false, true, true, true,  },
                { false, false, true, true, true, true,  },
                { false, true, true, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, true, true, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['5'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, false,  },
                { false, false, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['6'] = new bool[,]
            {
                { false, true, true, true, true, true,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['7'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, true, true, false,  },
                { false, false, true, true, false, false,  },
                { false, true, true, false, false, false,  },
                { false, true, true, false, false, false,  },
                { false, true, true, false, false, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['8'] = new bool[,]
            {
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['9'] = new bool[,]
            {
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, true,  },
                { false, false, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['a'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['b'] = new bool[,]
            {
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['c'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, true, true, true, true, true, true,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['d'] = new bool[,]
            {
                { false, false, false, false, false, true, true,  },
                { false, false, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['e'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, true,  },
                { true, true, false, false, false, false, false,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['f'] = new bool[,]
            {
                { false, false, true, true, false,  },
                { false, true, true, false, true,  },
                { false, true, true, false, false,  },
                { true, true, true, true, false,  },
                { false, true, true, false, false,  },
                { false, true, true, false, false,  },
                { false, true, true, false, false,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
            },
            ['g'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
            },
            ['h'] = new bool[,]
            {
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['i'] = new bool[,]
            {
                { true, true,  },
                { false, false,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { false, false,  },
                { false, false,  },
            },
            ['j'] = new bool[,]
            {
                { false, false, false, true, true,  },
                { false, false, false, false, false,  },
                { false, false, false, true, true,  },
                { false, false, false, true, true,  },
                { false, false, false, true, true,  },
                { false, false, false, true, true,  },
                { false, false, false, true, true,  },
                { true, true, false, true, true,  },
                { false, true, true, true, false,  },
            },
            ['k'] = new bool[,]
            {
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, true, true, false,  },
                { true, true, true, true, false, false,  },
                { true, true, false, true, true, false,  },
                { true, true, false, false, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['l'] = new bool[,]
            {
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { true, true,  },
                { false, false,  },
                { false, false,  },
            },
            ['m'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, true, false, false, true, true,  },
                { true, true, false, true, true, false, true,  },
                { true, true, false, true, true, false, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['n'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['o'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['p'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
            },
            ['q'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, true, true, true, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, true, true,  },
                { false, false, false, false, false, true, true,  },
            },
            ['r'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, false, true, true, true, false,  },
                { true, true, true, true, false, true, true,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['s'] = new bool[,]
            {
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
                { false, true, true, true, true, true,  },
                { true, true, false, false, false, false,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, true, true,  },
                { true, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['t'] = new bool[,]
            {
                { false, true, true, false, false,  },
                { false, true, true, false, false,  },
                { true, true, true, true, false,  },
                { false, true, true, false, false,  },
                { false, true, true, false, false,  },
                { false, true, true, false, false,  },
                { false, false, true, true, true,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
            },
            ['u'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['v'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, false, true, true, false,  },
                { false, false, true, true, true, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['w'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, true, true, false, true,  },
                { true, true, true, false, false, true, true,  },
                { false, true, true, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['x'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, false, true, true, false,  },
                { false, false, true, true, true, false, false,  },
                { false, true, true, false, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['y'] = new bool[,]
            {
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
            },
            ['z'] = new bool[,]
            {
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
                { true, true, true, true, true,  },
                { false, false, false, true, true,  },
                { false, true, true, true, false,  },
                { true, true, false, false, false,  },
                { true, true, true, true, true,  },
                { false, false, false, false, false,  },
                { false, false, false, false, false,  },
            },
            ['A'] = new bool[,]
            {
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['B'] = new bool[,]
            {
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['C'] = new bool[,]
            {
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['D'] = new bool[,]
            {
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['E'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['F'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, true,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['G'] = new bool[,]
            {
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, true, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['H'] = new bool[,]
            {
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['I'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { true, true, true, true, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['J'] = new bool[,]
            {
                { false, true, true, true, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['K'] = new bool[,]
            {
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, true, true, false,  },
                { true, true, false, true, true, false, false,  },
                { true, true, true, true, false, false, false,  },
                { true, true, false, true, true, false, false,  },
                { true, true, false, false, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['L'] = new bool[,]
            {
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['M'] = new bool[,]
            {
                { true, true, true, false, false, true, true,  },
                { true, true, true, true, true, true, true,  },
                { true, true, false, true, true, false, true,  },
                { true, true, false, true, true, false, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['N'] = new bool[,]
            {
                { true, true, true, false, false, true, true,  },
                { true, true, true, true, false, true, true,  },
                { true, true, false, true, true, true, true,  },
                { true, true, false, false, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['O'] = new bool[,]
            {
                { false, true, true, true, true, false,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['P'] = new bool[,]
            {
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { true, true, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['Q'] = new bool[,]
            {
                { false, true, true, true, true, true, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { true, true, false, true, true, false, true,  },
                { true, true, false, false, true, true, true,  },
                { false, true, true, true, true, true, true,  },
                { false, false, false, false, false, false, true,  },
                { false, false, false, false, false, false, false,  },
            },
            ['R'] = new bool[,]
            {
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, true, true, true, true, false,  },
                { true, true, false, false, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['S'] = new bool[,]
            {
                { false, true, true, true, true, true, false,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, false, false,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, true, true, true, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['T'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, true, true, false, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['U'] = new bool[,]
            {
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { true, true, false, false, true, true,  },
                { false, true, true, true, true, false,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
            ['V'] = new bool[,]
            {
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, true, true, false, true, true, false,  },
                { false, false, true, true, true, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['W'] = new bool[,]
            {
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, false, false, true, true,  },
                { true, true, false, true, false, true, true,  },
                { true, true, true, true, true, true, true,  },
                { true, true, true, false, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['X'] = new bool[,]
            {
                { true, true, false, false, false, true, true,  },
                { true, true, true, false, true, true, true,  },
                { false, true, true, true, true, true, false,  },
                { false, false, true, true, true, false, false,  },
                { false, true, true, true, true, true, false,  },
                { true, true, true, false, true, true, true,  },
                { true, true, false, false, false, true, true,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['Y'] = new bool[,]
            {
                { true, true, false, false, false, false, true,  },
                { true, true, false, false, false, false, true,  },
                { false, true, true, false, false, true, true,  },
                { false, false, true, true, true, true, false,  },
                { false, false, false, true, true, false, false,  },
                { false, false, false, true, true, false, false,  },
                { false, false, false, true, true, false, false,  },
                { false, false, false, false, false, false, false,  },
                { false, false, false, false, false, false, false,  },
            },
            ['Z'] = new bool[,]
            {
                { true, true, true, true, true, true,  },
                { false, false, false, false, true, true,  },
                { false, false, false, true, true, false,  },
                { false, false, true, true, false, false,  },
                { false, true, true, false, false, false,  },
                { true, true, false, false, false, false,  },
                { true, true, true, true, true, true,  },
                { false, false, false, false, false, false,  },
                { false, false, false, false, false, false,  },
            },
        };
    }
}
